from plyer.facades import FileChooser as FileChooser

class IOSFileChooser(FileChooser):
    def __init__(self, *args, **kwargs) -> None: ...
    def imagePickerController_didFinishPickingMediaWithInfo_(self, image_picker, frozen_dict) -> None: ...

def instance(): ...
