from _typeshed import Incomplete
from ctypes import Structure
from plyer.facades import Audio as Audio
from plyer.platforms.win.storagepath import WinStoragePath as WinStoragePath

ULONG_PTR: Incomplete
MCI_OPEN: int
MCI_OPEN_TYPE: int
MCI_OPEN_ELEMENT: int
MCI_RECORD: int
MCI_STOP: int
MCI_SAVE: int
MCI_PLAY: int
MCI_CLOSE: int
MCI_FROM: int
MCI_TO: int
MCI_WAIT: int
MCI_SAVE_FILE: int

class MCI_OPEN_PARMS(Structure): ...
class MCI_RECORD_PARMS(Structure): ...
class MCI_SAVE_PARMS(Structure): ...
class MCI_PLAY_PARMS(Structure): ...

def send_command(device, msg, flags, params): ...

class WinRecorder:
    def __init__(self, device, filename) -> None: ...
    @property
    def device(self): ...
    @property
    def filename(self): ...
    def record(self) -> None: ...
    def stop(self) -> None: ...

class WinPlayer:
    def __init__(self, device) -> None: ...
    @property
    def device(self): ...
    def play(self) -> None: ...
    def stop(self) -> None: ...

class WinAudio(Audio):
    def __init__(self, file_path=None) -> None: ...

def instance(): ...
