__all__ = ['WindowsBalloonTip', 'balloon_tip']

class WindowsBalloonTip:
    def __init__(self, title, message, app_name, app_icon: str = '', timeout: int = 10, **kwargs) -> None: ...
    def __del__(self) -> None: ...
    def notify(self, title, message, app_name) -> None: ...
    def remove_notify(self) -> None: ...

def balloon_tip(**kwargs) -> None: ...
