from plyer.facades import Notification as Notification
from plyer.utils import whereis_exe as whereis_exe

class NotifyDesktopPortals(Notification): ...
class NotifySendNotification(Notification): ...
class NotifyDbus(Notification): ...

def instance(): ...
