class Audio:
    state: str
    def __init__(self, file_path=None) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def play(self) -> None: ...
    @property
    def file_path(self): ...
    @file_path.setter
    def file_path(self, location) -> None: ...
