class Compass:
    @property
    def orientation(self): ...
    @property
    def field(self): ...
    @property
    def field_uncalib(self): ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def get_orientation(self): ...
    def get_field_uncalib(self): ...
