class CPU:
    @property
    def sockets(self): ...
    @property
    def physical(self): ...
    @property
    def logical(self): ...
    @property
    def cache(self): ...
    @property
    def numa(self): ...
