from _typeshed import Incomplete

class GPS:
    on_location: Incomplete
    on_status: Incomplete
    def configure(self, on_location, on_status=None) -> None: ...
    def start(self, minTime: int = 1000, minDistance: int = 1) -> None: ...
    def stop(self) -> None: ...
