class Gyroscope:
    @property
    def rotation(self): ...
    @property
    def rotation_uncalib(self): ...
    @property
    def orientation(self): ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def get_orientation(self): ...
    def get_rotation_uncalib(self): ...
