class IrBlaster:
    @staticmethod
    def periods_to_microseconds(frequency, pattern): ...
    @staticmethod
    def microseconds_to_periods(frequency, pattern): ...
    @property
    def frequencies(self): ...
    def get_frequencies(self): ...
    def transmit(self, frequency, pattern, mode: str = 'period'): ...
    def exists(self): ...
