class Orientation:
    def set_landscape(self, reverse: bool = False) -> None: ...
    def set_portrait(self, reverse: bool = False) -> None: ...
    def set_sensor(self, mode: str = 'any') -> None: ...
