class Screenshot:
    def __init__(self, file_path=None) -> None: ...
    def capture(self) -> None: ...
    @property
    def file_path(self): ...
    @file_path.setter
    def file_path(self, location) -> None: ...
