class StoragePath:
    def get_home_dir(self): ...
    def get_external_storage_dir(self): ...
    def get_sdcard_dir(self): ...
    def get_root_dir(self): ...
    def get_documents_dir(self): ...
    def get_downloads_dir(self): ...
    def get_videos_dir(self): ...
    def get_music_dir(self): ...
    def get_pictures_dir(self): ...
    def get_application_dir(self): ...
