from _typeshed import Incomplete

class STT:
    results: Incomplete
    errors: Incomplete
    partial_results: Incomplete
    prefer_offline: bool
    listening: bool
    @property
    def supported_languages(self): ...
    @property
    def language(self): ...
    @language.setter
    def language(self, lang) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def exist(self): ...
