from _typeshed import Incomplete

__all__ = ['platform', 'reify', 'deprecated']

class Platform:
    def __init__(self) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

platform: Incomplete

class Proxy:
    def __init__(self, name, facade) -> None: ...
    def __getattribute__(self, name): ...
    def __delattr__(self, name) -> None: ...
    def __setattr__(self, name, value) -> None: ...
    def __bool__(self) -> bool: ...

class reify:
    func: Incomplete
    __doc__: Incomplete
    def __init__(self, func) -> None: ...
    def __get__(self, inst, cls): ...

def deprecated(obj): ...
